### ISSUE TITLE
Documentation/Wiki

### ISSUE THREAD

**Issue by Microsamp** [CentauriCloud/Centauri-RestAPI#3]
We need a wiki or a documentation. There is no information about the port of the Jetty/Spark Server or something else. 

TODO:

What is the default port?
What are the encryption methods?
What are the endpoints?(and what are the giving back?)

**Comment by Microsamp** [comment]
Default port: 4567
Ps: http://prntscr.com/fqv8qi great html knowledge :D

**Comment by modev** [comment]
Yeah thats properly formatted HTML. The obly issue is the MIME type for the
page. I'd suggest a default JSON error page for poorly formatted requests

Microsamp <notifications@github.com> schrieb am Mo., 3. Juli 2017, 01:39:

**Comment by jsauvain** [comment]
This has already been implemented. The only issue was that an exception happened during the mapping of the routes.
